name: Build 

on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Setup Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    # Setup MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    # Setup NuGet
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    # Restore NuGet packages
    - name: Restore NuGet packages
      run: nuget restore Projeto-DotNet.sln

    # Cache SonarQube Cloud packages
    - name: Cache SonarQube Cloud packages
      uses: actions/cache@v4
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    # Cache SonarQube Cloud scanner
    - name: Cache SonarQube Cloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@v4
      with:
        path: .\.sonar\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner

    # Install SonarQube Cloud scanner
    - name: Install SonarQube Cloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        New-Item -Path .\.sonar\scanner -ItemType Directory
        dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

    # Begin SonarCloud analysis
    - name: Begin SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        .\.sonar\scanner\dotnet-sonarscanner begin /k:"${{ secrets.SONAR_PROJECT_KEY }}" `
          /o:"${{ secrets.SONAR_ORGANIZATION }}" `
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}" `
          /d:sonar.host.url="https://sonarcloud.io" `
          /d:sonar.verbose=true `
          /d:sonar.cs.opencover.reportsPaths="coverage/coverage.cobertura.xml"

    # Build the solution
    - name: Build solution
      run: msbuild Projeto-DotNetAppForms.sln /p:Configuration=Release

    # Add .NET tools to PATH
    - name: Add .NET tools to PATH
      run: echo "C:\\Users\\runneradmin\\.dotnet\\tools" >> ${{ runner.temp }}/path

    - name: Update PATH
      run: echo "${{ runner.temp }}/path" >> $GITHUB_PATH

    # End SonarCloud analysis
    - name: End SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./.sonar/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}